name: Coffee
favicon: null
layout_spectrum: 0.89001
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#edebee'
    - '#070705'
    - '#b3b8bc'
    - '#493c2b'
    - '#db933f'
  brandStrength: 0.75
  lightness: 0.1875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
