name: null
favicon: null
layout_spectrum: 0.08512
typography_spectrum: 0.01494
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2f3831'
    - '#66685d'
    - '#e3b678'
    - '#d47b34'
    - '#e2e8e8'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
