name: Coffee
favicon: null
layout_spectrum: 0.56225
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#454753'
    - '#f8f0ee'
    - '#8d86b2'
    - '#9e555a'
    - '#e6795e'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
